name: Run MicroTrendHunter hourly

on:
  schedule:
    # runs every hour at minute 0
    - cron: '0 * * * *'
  workflow_dispatch:  # manual trigger option

jobs:
  run_microtrend:
    runs-on: ubuntu-latest
    env:
      GNEWS_API: ${{ secrets.GNEWS_API }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run MicroTrendHunter pipeline
        run: python main.py
